
spring:
  datasource:
    url: jdbc:mysql://j4c101.p.ssafy.io:3306/cooksistant?serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use-new-id-generator-mappings: false
    generate-ddl: true
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket: s3-recipe-img
    region:
      static: us-east-1
    stack:
      auto: false