spring:
  datasource:
    url: jdbc:mysql://j4C101.p.ssafy.io:3306/cookssistant?serverTimezone=Asia/Seoul
    username: root
    password: root
    #    url: jdbc:mysql://localhost:3306/hunsu?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    #    username: ssafy
    #    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
